### ISSUE TITLE
Nested scss is fails to parse correctly.

### ISSUE THREAD

**Issue by summer-mute** [tommasongr/nova-vue#46]
It seems like this subsyntax fails to match for nested scss.

```xml
<subsyntax name="scss">
	<cut-off>
		<expression>(?=&lt;/(?i:style)\b)</expression>
	</cut-off>
</subsyntax>						
```
here is an example from a `.sass` file of nested selectors highlighting correctly 

<img width="724" alt="Screen Shot 2022-04-21 at 11 56 40 AM" src="https://user-images.githubusercontent.com/38389951/164512117-bc3656eb-c924-4458-9578-fdbda174b11b.png">

here is the most basic pathological example in a `.vue` file: 
<img width="724" alt="Screen Shot 2022-04-21 at 11 59 35 AM" src="https://user-images.githubusercontent.com/38389951/164512744-b3f07ae7-34a1-4925-93d4-99393ccbfa5e.png">

I tried changing the `subsyntax` to a `subscopes`  but either I dont know how to correctly make changes to installed plugins or this doesn't fix the problem.
```xml
<subscopes repeat="true">
        <include syntax="scss" />
</subscopes>
```

**Comment by tommasongr** [comment]
Hi there!

Oh gosh! Thanks for the catch!
I looked at it and it was worst than you initially find out... Apparently all the not standard syntaxes both for css and javascript were ignored all together. It was a matter of the order in which the alternative scopes were specified in the syntax. I'm so 
sorry for this... I usually stick to the standard css and js and I have never come across this.

<img width="924" alt="CleanShot 2022-04-21 at 21 58 29@2x" src="https://user-images.githubusercontent.com/25225746/164543760-37659152-877e-49d0-bf50-ad4055b909f8.png">

I'll push the fix ASAP

**Comment by summer-mute** [comment]
Thanks man, I use the tool everyday, really nice work.

**Comment by tommasongr** [comment]
Just pushed v5.4 with the fix! Let me know if it works

By the way stay tuned for a major update in the coming days. I'm looking at leaving Vetur for the new Volar language server.

**Comment by summer-mute** [comment]
@tommasongr Thanks, nested class selectors are working properly now, however it looks like there is still some issues parsing at-rules. 

Here is a test snippet.

```scss
.icon-grid {
  @media (max-width: calc(#{$lg} - 1px)) {
    grid-template-columns: 1fr;
  }
  .grid-item {

    @media (max-width: calc(#{$lg} - 1px)) {
      padding-bottom: 5.7rem;
    }
    h4 {
      @media (max-width: calc(#{$lg} - 1px)) {
        padding: 2rem 0 0.6rem;
      }
    }

    img {
      @media (max-width: calc(#{$lg} - 1px)) {
        height: 7.5rem;
      }
    }
  }
}
```
in a `.vue` file:

<img width="822" alt="Screen Shot 2022-04-22 at 11 14 11 AM" src="https://user-images.githubusercontent.com/38389951/164753878-25b36907-5d88-4b6c-aac1-484063a43b38.png">

in a `.scss` file:

<img width="720" alt="Screen Shot 2022-04-22 at 11 14 59 AM" src="https://user-images.githubusercontent.com/38389951/164754007-bf529ac0-93ee-442d-b1da-501c5e4b8be0.png">

Let me know if I can provide any additional information.
